default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Description of what the lane does"
  lane :tests_master do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(scheme: "RxSwift-Memo-SampleTests")
  end
end
